package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, dir, name, body string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestRunPassesUnderBudget(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "small.go", "package fixture\n\nvar X = 1\n")
	var stdout, stderr strings.Builder
	if err := run([]string{"--root", dir, "--max", "100", "--files-from", "-"},
		strings.NewReader("small.go\n"), &stdout, &stderr); err != nil {
		t.Fatalf("run: %v (%s)", err, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("violations printed for a passing scan: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "1 files") {
		t.Fatalf("summary missing: %q", stderr.String())
	}
}

func TestRunFailsOnViolationWithOverage(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "big.go", "package fixture\n\n"+strings.Repeat("// padding\n", 40))
	var stdout, stderr strings.Builder
	err := run([]string{"--root", dir, "--max", "10", "--files-from", "-"},
		strings.NewReader("big.go\n"), &stdout, &stderr)
	if err == nil {
		t.Fatal("over-budget file accepted")
	}
	line := strings.TrimSpace(stdout.String())
	if !strings.HasPrefix(line, "big.go") && !strings.Contains(line, "\tbig.go\t(+") {
		t.Fatalf("violation line = %q", line)
	}
	if !strings.Contains(stderr.String(), "1 violation(s)") {
		t.Fatalf("summary = %q", stderr.String())
	}
}

func TestRunVerboseListsEveryFileSortedByTokens(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.go", "package fixture\n")
	writeFile(t, dir, "b.go", "package fixture\n\nvar Longer = \"padding padding padding\"\n")
	var stdout, stderr strings.Builder
	if err := run([]string{"--root", dir, "--max", "1000", "--verbose", "--files-from", "-"},
		strings.NewReader("a.go\nb.go\n"), &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimSpace(stdout.String()), "\n")
	if len(lines) != 2 || !strings.HasSuffix(lines[0], "b.go") || !strings.HasSuffix(lines[1], "a.go") {
		t.Fatalf("verbose output = %v", lines)
	}
}

func TestRunJSONReport(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.go", "package fixture\n")
	writeFile(t, dir, "generated.go", "// Code generated by tool. DO NOT EDIT.\n\npackage fixture\n")
	var stdout, stderr strings.Builder
	if err := run([]string{"--root", dir, "--json", "--files-from", "-"},
		strings.NewReader("a.go\ngenerated.go\n"), &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var payload struct {
		Encoding  string `json:"encoding"`
		MaxTokens int    `json:"maxTokens"`
		Files     []struct {
			Path   string
			Tokens int
		} `json:"files"`
		Skipped []struct {
			Path string
		} `json:"skipped"`
	}
	if err := json.Unmarshal([]byte(stdout.String()), &payload); err != nil {
		t.Fatalf("json: %v (%s)", err, stdout.String())
	}
	if payload.Encoding != "o200k_base" || payload.MaxTokens != 3000 {
		t.Fatalf("payload = %+v", payload)
	}
	if len(payload.Files) != 1 || payload.Files[0].Path != "a.go" || payload.Files[0].Tokens == 0 {
		t.Fatalf("files = %+v", payload.Files)
	}
	if len(payload.Skipped) != 1 || payload.Skipped[0].Path != "generated.go" {
		t.Fatalf("skipped = %+v", payload.Skipped)
	}
	// Empty lists are arrays, never null.
	if !strings.Contains(stdout.String(), `"offending": []`) {
		t.Fatalf("empty offending list is not an array: %s", stdout.String())
	}
}

// TestRunJSONReportFailsOnViolation: --json changes the output format,
// never the exit contract — the complete report is emitted, it stays
// parseable, and the scan still fails.
func TestRunJSONReportFailsOnViolation(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "big.go", "package fixture\n\n"+strings.Repeat("// padding\n", 40))
	var stdout, stderr strings.Builder
	err := run([]string{"--root", dir, "--max", "10", "--json", "--files-from", "-"},
		strings.NewReader("big.go\n"), &stdout, &stderr)
	if err == nil {
		t.Fatal("over-budget file accepted under --json")
	}
	var payload struct {
		Encoding  string `json:"encoding"`
		MaxTokens int    `json:"maxTokens"`
		Offending []struct {
			Path   string `json:"path"`
			Tokens int    `json:"tokens"`
		} `json:"offending"`
		Skipped []struct {
			Path string `json:"path"`
		} `json:"skipped"`
	}
	if err := json.Unmarshal([]byte(stdout.String()), &payload); err != nil {
		t.Fatalf("json report missing or malformed: %v (%s)", err, stdout.String())
	}
	if payload.Encoding != "o200k_base" || payload.MaxTokens != 10 {
		t.Fatalf("payload = %+v", payload)
	}
	if len(payload.Offending) != 1 || payload.Offending[0].Path != "big.go" || payload.Offending[0].Tokens <= 10 {
		t.Fatalf("offending = %+v", payload.Offending)
	}
	if !strings.Contains(stdout.String(), `"skipped": []`) {
		t.Fatalf("empty skipped list is not an array: %s", stdout.String())
	}
}

func TestRunRejectsConflictingSelectors(t *testing.T) {
	var stdout, stderr strings.Builder
	if err := run([]string{"--all", "--base", "HEAD"}, strings.NewReader(""), &stdout, &stderr); err == nil {
		t.Fatal("conflicting selectors accepted")
	}
	if err := run([]string{"extra.go", "--all"}, strings.NewReader(""), &stdout, &stderr); err == nil {
		t.Fatal("positional arguments accepted")
	}
}

func TestRunReportsUnsafePaths(t *testing.T) {
	dir := t.TempDir()
	var stdout, stderr strings.Builder
	if err := run([]string{"--root", dir, "--files-from", "-"},
		strings.NewReader("../escape.go\n"), &stdout, &stderr); err == nil {
		t.Fatal("unsafe path accepted")
	}
}

func TestRunAllUsesGitEnumeration(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.go", "package fixture\n")
	runGit(t, dir, "init", "--quiet")
	runGit(t, dir, "add", "a.go")
	runGit(t, dir, "-c", "user.email=gate@example.com", "-c", "user.name=gate",
		"commit", "--quiet", "-m", "initial")
	writeFile(t, dir, "untracked.go", "package fixture\n")
	var stdout, stderr strings.Builder
	if err := run([]string{"--root", dir, "--all", "--verbose"}, strings.NewReader(""), &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stdout.String(), "untracked.go") || !strings.Contains(stderr.String(), "2 files") {
		t.Fatalf("stdout=%q stderr=%q", stdout.String(), stderr.String())
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, out)
	}
}
