package gofiles

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// newRepo creates a throwaway git repository with one commit.
func newRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	run(t, dir, "init", "--quiet")
	write(t, dir, "tracked.go", "package fixture\n")
	write(t, dir, "dir with space/spaced.go", "package fixture\n")
	run(t, dir, "add", "-A")
	run(t, dir, "-c", "user.email=gate@example.com", "-c", "user.name=gate",
		"commit", "--quiet", "-m", "initial")
	return dir
}

func run(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, out)
	}
}

func write(t *testing.T, dir, name, body string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestListFullTreeIncludesTrackedUntrackedAndSpaces(t *testing.T) {
	dir := newRepo(t)
	write(t, dir, "untracked.go", "package fixture\n")
	write(t, dir, "ignored.go", "package fixture\n")
	write(t, dir, ".gitignore", "ignored.go\n")
	write(t, dir, "notes.md", "not go\n")

	paths, err := List(context.Background(), Options{Root: dir})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"dir with space/spaced.go", "tracked.go", "untracked.go"}
	if strings.Join(paths, ",") != strings.Join(want, ",") {
		t.Fatalf("paths = %v, want %v", paths, want)
	}
}

func TestListChangedAgainstBase(t *testing.T) {
	dir := newRepo(t)
	base := strings.TrimSpace(gitOutput(t, dir, "rev-parse", "HEAD"))
	write(t, dir, "tracked.go", "package fixture\n\nvar Changed = true\n")
	write(t, dir, "added.go", "package fixture\n")
	write(t, dir, "deleted.go", "package fixture\n")
	run(t, dir, "add", "added.go", "deleted.go")
	run(t, dir, "-c", "user.email=gate@example.com", "-c", "user.name=gate",
		"commit", "--quiet", "-m", "add")
	run(t, dir, "rm", "--quiet", "deleted.go")
	run(t, dir, "-c", "user.email=gate@example.com", "-c", "user.name=gate",
		"commit", "--quiet", "-m", "remove")
	write(t, dir, "untracked.go", "package fixture\n")

	paths, err := List(context.Background(), Options{
		Root: dir,
		Base: base,
	})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"added.go", "tracked.go", "untracked.go"}
	if strings.Join(paths, ",") != strings.Join(want, ",") {
		t.Fatalf("paths = %v, want %v", paths, want)
	}
}

func TestListRejectsUnknownBase(t *testing.T) {
	dir := newRepo(t)
	if _, err := List(context.Background(), Options{
		Root: dir,
		Base: "no-such-rev",
	}); err == nil {
		t.Fatal("unknown base accepted")
	}
}

func TestNormalizeRejectsUnsafePaths(t *testing.T) {
	for _, bad := range []string{"../escape.go", "/abs.go", "a/../../b.go"} {
		if _, err := Normalize([]string{bad}); err == nil {
			t.Fatalf("unsafe path accepted: %s", bad)
		}
	}
	got, err := Normalize([]string{" b.go ", "a.go", "a.go", ""})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(got, ",") != "a.go,b.go" {
		t.Fatalf("normalized = %v", got)
	}
}

func TestGeneratedDetection(t *testing.T) {
	cases := []struct {
		name     string
		source   string
		expected bool
	}{
		{"standard header", "// Code generated by tool. DO NOT EDIT.\n\npackage a\n", true},
		{"header after package", "package a\n\n// Code generated by tool. DO NOT EDIT.\n", false},
		{"no header", "package a\n\nvar X = 1\n", false},
		{"similar but not exact", "// Code generated by tool; do not edit.\npackage a\n", false},
		{"unparsable", "package\n", false},
	}
	for _, tc := range cases {
		if got := Generated("fixture.go", []byte(tc.source)); got != tc.expected {
			t.Fatalf("%s: Generated = %v, want %v", tc.name, got, tc.expected)
		}
	}
}

func gitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("git %s: %v", strings.Join(args, " "), err)
	}
	return string(out)
}
