// Package term wraps gitpod-io/xterm-go as RepoSuite Relay's headless
// terminal model. It owns the host-side responsibilities xterm.js delegates
// to its embedder: color-palette queries (OSC 4/10/11/12) and delivery of
// terminal-generated reply bytes (DA, DSR, CPR, DECRQM, kitty keyboard).
//
// The model is the terminal peer of a child process: raw PTY output goes in
// via Write, and the terminal's generated responses leave via the ReplyFunc,
// which the caller wires back to the PTY master.
package term

import (
	"fmt"

	xterm "github.com/gitpod-io/xterm-go"
)

// Color indices beyond the 256-color palette, matching xterm-go's
// SpecialColorIndex values for OSC 10/11/12.
const (
	specialFg = int(xterm.SpecialColorForeground) // 256
	specialBg = int(xterm.SpecialColorBackground) // 257
	specialCs = int(xterm.SpecialColorCursor)     // 258
	paletteSz = 259
)

// Model is a headless terminal with host services attached.
type Model struct {
	Term       *xterm.Terminal
	serializer *xterm.SerializeAddon

	reply func([]byte)

	palette    [paletteSz]xterm.ColorRGB
	paletteSet [paletteSz]bool
}

// Options configures the model.
type Options struct {
	Cols       int
	Rows       int
	Scrollback int
	// Reply receives terminal-generated bytes (query answers). It is invoked
	// synchronously from inside Write; implementations must not block.
	Reply func([]byte)
	// Fg/Bg are the default colors the host reports for OSC 10/11 queries.
	Fg xterm.ColorRGB
	Bg xterm.ColorRGB
}

// New creates a headless terminal model.
func New(opts Options) *Model {
	m := &Model{reply: opts.Reply}
	if m.reply == nil {
		m.reply = func([]byte) {}
	}
	m.initPalette(opts.Fg, opts.Bg)

	m.Term = xterm.New(
		xterm.WithCols(opts.Cols),
		xterm.WithRows(opts.Rows),
		xterm.WithScrollback(opts.Scrollback),
		// Enable the kitty keyboard VT extension so CSI ?u / CSI >u / CSI =u
		// behave like xterm.js with vtExtensions.kittyKeyboard enabled.
		xterm.WithVtExtensions(xterm.VtExtensions{KittyKeyboard: true}),
	)
	m.serializer = xterm.NewSerializeAddon(m.Term)
	m.Term.OnData(func(s string) { m.reply([]byte(s)) })
	m.Term.OnColor(m.onColor)
	return m
}

// initPalette seeds the 256-color xterm palette plus the default special
// colors, matching what a real terminal would report.
func (m *Model) initPalette(fg, bg xterm.ColorRGB) {
	base16 := [16]xterm.ColorRGB{
		{0x00, 0x00, 0x00}, {0xcd, 0x00, 0x00}, {0x00, 0xcd, 0x00}, {0xcd, 0xcd, 0x00},
		{0x00, 0x00, 0xee}, {0xcd, 0x00, 0xcd}, {0x00, 0xcd, 0xcd}, {0xe5, 0xe5, 0xe5},
		{0x7f, 0x7f, 0x7f}, {0xff, 0x00, 0x00}, {0x00, 0xff, 0x00}, {0xff, 0xff, 0x00},
		{0x5c, 0x5c, 0xff}, {0xff, 0x00, 0xff}, {0x00, 0xff, 0xff}, {0xff, 0xff, 0xff},
	}
	copy(m.palette[:16], base16[:])
	// 216-color cube: levels {0,95,135,175,215,255}.
	levels := [6]uint8{0, 95, 135, 175, 215, 255}
	for i := 0; i < 216; i++ {
		m.palette[16+i] = xterm.ColorRGB{levels[i/36], levels[(i/6)%6], levels[i%6]}
	}
	for i := 0; i < 24; i++ {
		v := uint8(8 + i*10)
		m.palette[232+i] = xterm.ColorRGB{v, v, v}
	}
	m.palette[specialFg] = fg
	m.palette[specialBg] = bg
	m.palette[specialCs] = xterm.ColorRGB{0xff, 0xff, 0xff}
	for i := range m.palette {
		m.paletteSet[i] = true
	}
}

// Write feeds raw child output into the terminal. Reply bytes (if any) are
// emitted synchronously via the configured Reply callback.
func (m *Model) Write(p []byte) (int, error) { return m.Term.Write(p) }

// Snapshot serializes the terminal state as replayable escape sequences.
// scrollback<0 includes all scrollback; scrollback==0 is viewport-only.
func (m *Model) Snapshot(scrollback int) []byte {
	var sb *int
	if scrollback >= 0 {
		sb = &scrollback
	}
	return m.serializer.Serialize(&xterm.SerializeOptions{Scrollback: sb})
}

// onColor answers OSC 4/10/11/12 set/query/restore requests. xterm-go, like
// xterm.js, delegates palette ownership to the host; we are the host.
func (m *Model) onColor(events []xterm.ColorEvent) {
	for _, ev := range events {
		switch ev.Type {
		case xterm.ColorRequestSet:
			if ev.Color != nil && ev.Index >= 0 && ev.Index < paletteSz {
				m.palette[ev.Index] = *ev.Color
			}
		case xterm.ColorRequestReport:
			m.reportColor(ev.Index)
		case xterm.ColorRequestRestore:
			if ev.Index < 0 || ev.Index >= paletteSz {
				m.initPalette(m.palette[specialFg], m.palette[specialBg])
			}
		}
	}
}

// reportColor emits the standard xterm-style color report for a palette or
// special color index: OSC 4;idx;spec for indexed colors, OSC 10/11/12 for
// the special slots. Format matches real xterm replies: rgb:rrrr/gggg/bbbb
// with 16-bit channels.
func (m *Model) reportColor(index int) {
	if index < 0 || index >= paletteSz {
		return
	}
	c := m.palette[index]
	spec := fmt.Sprintf("rgb:%02x%02x/%02x%02x/%02x%02x", c[0], c[0], c[1], c[1], c[2], c[2])
	var ident int
	switch index {
	case specialFg:
		ident = 10
	case specialBg:
		ident = 11
	case specialCs:
		ident = 12
	default:
		m.reply([]byte(fmt.Sprintf("\x1b]4;%d;%s\x1b\\", index, spec)))
		return
	}
	m.reply([]byte(fmt.Sprintf("\x1b]%d;%s\x1b\\", ident, spec)))
}

// Dispose releases terminal resources.
func (m *Model) Dispose() { m.Term.Dispose() }
